image/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from . import views
app_name='image'
urlpatterns = [
    url(r'^upload/$', views.UploadImage.as_view(), name='upload'),
    url(r'^details/(?P<pk>[0-9]+)$', views.DetailView.as_view(), name='details'),
    url(r'^$', views.IndexView.as_view(), name='index'),

]

untitled2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from image import views
from django.conf.urls.static import static

from untitled2 import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('image/', include('image.urls')),
    path('', views.IndexView.as_view(), name="index" ),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

image/models.py
from django.db import models
from django.urls import reverse


class Images(models.Model):
    title=models.CharField(max_length=120)
    content=models.TextField()
    imagesrc=models.FileField()
    hashvalue=models.CharField(max_length=32,null=True,blank=True)

    def get_absolute_url(self):
        return reverse('image:details', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

    def __int__(self, title, content, imagesrc, hashvalue):
        self.title=title
        self.content=content
        self.imagesrc=imagesrc
        self.hashvalue=hashvalue

image/forms.py
from .models import Images
from django import forms

class ImageForm(forms.ModelForm):
        class Meta:
            model=Images
            fields = ['title','content','imagesrc']

image/views.py
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.shortcuts import render, redirect
from django.views import generic,View
from .forms import ImageForm
from django.http import HttpResponse
import os
from untitled2 import settings
from .models import Images
import hashlib

@receiver (post_save, sender=Images )
def generate_hash(instance, update_fields, *args, **kwargs ):

    #generate hash value of instance image
    name = os.path.basename(instance.imagesrc.name)
    filename = os.path.join(settings.BASE_DIR, 'media/')
    hasher=hashlib.md5()
    with open(os.path.join(filename, name), 'rb') as open_file:
        content=open_file.read()
        hasher.update(content)
    value=hasher.hexdigest()

    #retrieve hashvalues from database
    e=Images.objects.all().values_list('hashvalue')
    result = []
    for t in e:
        for x in t:
            result.append(x)
    print (result)

    #checking for duplicate image
    if value in result:
        print('duplicate Image')
        Images.objects.filter(id=instance.id).delete()
        return False

    else:
        #print(value)
        print("new image")
        instance.hashvalue=value
        post_save.disconnect(generate_hash, sender=Images)
        instance.save(update_fields={'hashvalue'})
        post_save.connect(generate_hash, sender=Images)
        return True

class UploadImage(View):
    form_class=ImageForm
    template_name='image/form.html'
    fields = ['title','content','imagesrc']

    def get (self, request):
        form=self.form_class(None)
        return render(request, self.template_name, {'form':form})

    def post (self, request):
        form=self.form_class(request.POST, request.FILES)
        if form.is_valid():
           a= form.save()
           if a.hashvalue is not None:
               return redirect('image:index')
               exit()
        return HttpResponse('<h1>DUplicate Image</h1>')

class IndexView(generic.ListView):
    template_name = 'image/index.html'
    def get_queryset(self):
        return Images.objects.all()

class DetailView(generic.DetailView):
    model = Images
    template_name = 'image/details.html'

image/templates/image/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details</title>
    {% load staticfiles %}
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'image/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
       <nav class="navbar navbar-inverse"  >
        <div class="container-fluid">
            <!-- Header -->
            <div class="navbar-header">
                <!--whenever browser window size is decreased, all nav bar items will be listed through this button -->
                <button type="button" class="navbar-toggle" data_toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'image:index' %}">Images</a>
            </div>
            <!-- items-->
            <div class="collapse navbar-collapse" id="topNavBar">
                 <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'image:upload' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                            Add Image
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
        <img src="{{ images.imagesrc.url }}"><br>
        <h1>{{images.title}}</h1><br>
        <h3> {{ images.content }}</h3>
</body>
</html>

image/templates/image/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>Form</title>
</head>
<body>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
    <div>
        <div>
            <span>{{field.errors}}</span>
        </div>
        <label>
            {{ field.label_tag}}
        </label>
        <div>
            {{field}}
        </div>
    </div>
{% endfor %}
    <button type="submit">Submit</button>
</form>



</body>
</html>

image/templates/image/index.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Images</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'image/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse"  >
        <div class="container-fluid">
            <!-- Header -->
            <div class="navbar-header">
                <!--whenever browser window size is decreased, all nav bar items will be listed through this button -->
                <button type="button" class="navbar-toggle" data_toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'image:index' %}">Images</a>
            </div>
            <!-- items-->
            <div class="collapse navbar-collapse" id="topNavBar">
                 <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'image:upload' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                            Add Image
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% for image in object_list %}
        <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="#">
                            <img src="{{ image.imagesrc.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ image.title}}</h2>
                            <h4>{{ image.content }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'image:details' image.pk %}" class="btn btn-primary btn-sm" role="button">View Detail</a>
                        </div>
                    </div>
        </div>
    {% endfor %}



</body>
</html>